---
engines:
  brakeman:
    enabled: true
  bundler-audit:
    enabled: true
  coffeelint:
    enabled: true
  duplication:
    enabled: true
    config:
      languages:
        - ruby
        - javascript
  eslint:
    enabled: true
  fixme:
    enabled: true
  reek:
    enabled: true
  rubocop:
    enabled: true
  scss-lint:
    enabled: true
ratings:
  paths:
    - Gemfile.lock
    - "**.coffee"
    - "**.erb"
    - "**.js"
    - "**.rb"
exclude_paths:
  - config/
  - db/
  - spec/
  - test/
  - vendor/
