---
engines:
  brakeman:
    enabled: true
  bundler-audit:
    enabled: true
  coffeelint:
    enabled: true
  duplication:
    enabled: true
    config:
      languages:
        - ruby
        - javascript
  eslint:
    enabled: true
  fixme:
    enabled: true
  reek:
    enabled: true
  rubocop:
    enabled: true
  scss-lint:
    enabled: true
ratings:
  paths:
    - Capfile
    - Gemfile
    - Gemfile.lock
    - Rakefile
    - config.ru
    - "**.coffee"
    - "**.js"
    - "**.prawn"
    - "**.rb"
    - "**.scss"
exclude_paths:
  - LICENSE
  - bin/
  - config/
  - db/
  - spec/
  - test/
  - vendor/
  - "**.erb"
  - "**.html"
  - "**.ico"
  - "**.json"
  - "**.md"
  - "**.png"
  - "**.txt"
  - "**.yml"
