---
require:
  - rubocop-rspec

inherit_from:
  - .rubocop_defaults.yml
  - .rubocop_cc.yml

AllCops:
  Include:
    - '**/config.ru'
    - '**/Gemfile'
    - '**/Rakefile'
    - '**/Capfile'
    - '**/*.prawn'
