---
require:
  - rubocop-rspec

inherit_from:
  - https://raw.githubusercontent.com/thoughtbot/guides/master/style/ruby/.rubocop.yml

AllCops:
  Include:
    - '**/config.ru'
    - '**/Gemfile'
    - '**/Rakefile'
    - '**/Capfile'
    - '**/*.prawn'
