name: CI

on:
  push:
    branches:
      - master

jobs:
  tests:
    name: Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Ruby and Install Gems
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '2.2.10'
          bundler-cache: true

      - name: Setup Node
        uses: actions/setup-node@v1

      - name: Setup Test Database
        env:
          RAILS_ENV: test
        run: |
          bundle install -with test
          rake db:create
          rake db:schema:load
          bundle exec rspec
